### PR TITLE
Custom xassets loading

### PR DESCRIPTION
**Pull request by ate47**
Hello,

to link with the previous PR, here a pull request to load custom xassets.

For now it supports these types:

- `scriptparsetree` - scripts (.gsc/.csc/.gsic/.csic) for replacement and auto linking
- `rawfile` - raw file
- `luafile` - compiled Lua HKS (only replacement)
- `stringtable` - csv file (.csv)

## Mods

To load them I created a directory in the Black Ops 4 install `project-bo4/mods`.

In it the user has to create a directory with a json file `metadata.json` in it.

For example `project-bo4\mods\demo_mod\metadata.json`.

The format of this json is:

```json
{
    "name": "Demo mod",
    "data": [
        {
            "type": "asset type",
            "name": "path in game",
            "path": "path from the mod dir or absolute"
        }
    ]
}
```

More configs are available in the script config.

## Scripts

It is possible to load script file with the support of GSIC file, a custom format from the T8-Compiler to replace script functions from the game.

To inject a script, 2 ways are possible, to replace an already existing one or to inject a new one. To tell the game when an injected script should be loaded, a hook script config is available. When a hook script is loaded, the injected script will be loaded.

The hooks of a script are defined with the `"hooks": [ "hook.gsc" ]` config. For example the script demo.gsc loaded when the script zm_common/load.gsc is loaded.

```json
{
    "name": "Demo mod",
    "data": [
        {
            "type": "scriptparsetree",
            "name": "scripts/shield/demo.gsc",
            "path": "compiled.gsic",
            "hooks": [
                "scripts/zm_common/load.gsc"
            ]
        }
    ]
}

```

## String tables

The game is using "compiled" csv files, these files have the cell values compiled instead of storing the string values. For example with [zm_mansion_weapons.csv](https://github.com/ate47/bo4-source/blob/main/gamedata/weapons/zm/zm_mansion_weapons.csv), the table to tell the weapon loaded by a map, the weapon names are hashes.

To create custom table, I've made a code to load the CSV with the first line used to tell the type of the columns. These types are:

- string
- int
- hash
- float
- undefined (gsc)

For example with all the available types:

```csv
string,int,hash,bool,float,undefined
aaa,123,ar_accurate_t8,true,6.7,
bbb,456,hash_123456789,false,13.823,
ccc,789,ar_accurate_t8,true,12.6,
```

## Command

I've added the command `shield_load_mods` for the console to reload at runtime the mods, it only works if the user is in the UI level to avoid reloading scripts in game.

## Future

I can explain some parts if required.

The replacement/injection of the xassets is only done with scripts, csv, rawfiles, but we can imagine doing something similar with models, materials and images. (If someone wants to search for it)

### CODE REVIEW

**Comment by bodnjenie14** [comment]
nice work ate :)

**Comment by NotNierPea** [comment]
pretty nice, finally loading mods without compiler lol

**Comment by project-bo4** [comment]
Nice job but few correction/changes needed first:
1-  **metadata.json** is named **mod.json** in code.
2- for the command name i think something like reload_mods would fit better.
3- there are some unformatted comments inbetween code about json templates needed to be trimmed.

**Comment by ate47** [comment]
It should be better. About the 1st point, were you talking about what I've replaced or something else?

**Comment by project-bo4** [comment]
looks good now. btw if you have any raw template mod(something basic like basic hud) just to showcase how this works we can add in project source in its relative path.

p.s: about 1st point idk why but github sorts commits history in descending order (by date) and i had seen your oldest commit just quickly browsing so its ok now

**Comment by bodnjenie14** [comment]
> looks good now. btw if you have any raw template mod(something basic like basic hud) just to showcase how this works we can add in project source in its relative path.
> 
> p.s: about 1st point idk why but github sorts commits history in descending order (by date) and i had seen your oldest commit just quickly browsing so its ok now

Our server has them #shield-mods (use the basic zombie counter mod ) or use the showcase images I sent on telegram

**Comment by ate47** [comment]
Like bod said you have this channel, but I've also made a repo with some mods

The best example imo is this one:

https://github.com/ate47/shield_mods/tree/main/custom_skins

It shows how we can easily combine CSVs and GSCs

**Pull request merged**
